# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('watched', models.BooleanField(default=True)),
                ('douban_id', models.CharField(max_length=60)),
                ('imdb_id', models.CharField(blank=True, max_length=60)),
                ('date_watched', models.DateTimeField(auto_now_add=True)),
                ('original_title', models.CharField(blank=True, max_length=60)),
                ('year', models.IntegerField(blank=True, default=0)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('images', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('visual_type', models.ManyToManyField(blank=True, to='visual.Type')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
