# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visual',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
