# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_auto_20160722_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 17, 18, 4, 724887, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
