# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visual', '0005_visual_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='favorite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
